export interface PowerLevelMetrics {
  id: string;
  match_id: string;
  puuid: string;
  champion_name: string;
  role_position: "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "SUPPORT";
  champ_level: number;
  game_duration: number;
  game_start_time: string;
  game_minutes: number;
  win: boolean;
  kills: number;
  deaths: number;
  assists: number;
  kda: number;
  total_damage_dealt: number;
  total_damage_taken: number;
  damage_per_minute: number | null;
  team_damage_percentage: number | null;
  damage_taken_on_team_percentage: number | null;
  total_gold: number | null;
  gold_per_minute: number | null;
  cs_count: number | null;
  cs_per_minute: number | null;
  vision_score: number | null;
  wards_placed: number | null;
  wards_destroyed: number | null;
  vision_score_per_minute: number | null;
  dragons_killed: number | null;
  barons_killed: number | null;
  heralds_killed: number | null;
  turrets_destroyed: number | null;
  turret_plates_taken: number | null;
  skillshots_hit: number | null;
  skillshot_accuracy: number | null;
  skillshots_dodged: number | null;
  immobilize_and_kill: number | null;
  solo_kills: number | null;
  outnumbered_kills: number | null;
  double_kills: number | null;
  triple_kills: number | null;
  quadra_kills: number | null;
  penta_kills: number | null;
  killing_sprees: number | null;
  largest_killing_spree: number | null;
  first_blood_taken: boolean | null;
  first_blood_assist: boolean | null;
  kill_participation: number | null;
  full_team_takedowns: number | null;
  save_ally_from_death: number | null;
  pick_kill_with_ally: number | null;
  kill_after_hidden: number | null;
  longest_time_living: number | null;
  time_spent_dead: number | null;
  survived_three_immobilizes: number | null;
  deaths_by_enemy_champs: number | null;
  time_ccing_others: number | null;
  enemy_immobilizations: number | null;
  legendary_items_count: number | null;
  max_level_lead: number | null;
  takedowns_first_10min: number | null;
  flawless_aces: number | null;
  perfect_game: boolean | null;
}
