"use client";
import React, { useState, useEffect } from 'react';
// Import Head to manage the <head> tag, e.g., for the title
// import Head from 'next/head'; // TODO: Address this causing compilation error generated by Gemini and meanwhile disabled

// Import Link for Next.js client-side navigation.
// We aren't using it in this single-file setup, but I've included comments
// on how to refactor to use it.
// import Link from 'next/link';

// Import icons from a library like 'lucide-react'.
// Since I can't assume you have it installed, I'll use simple text/SVG placeholders.
// Example: import { Home, BarChart3, Swords, Play } from 'lucide-react';

/*
================================================================================
== NEXT.JS REFACTORING GUIDE (How to split this file) ==
================================================================================

This single file simulates a multi-page app using React state (the `currentPage`
variable). To convert this to a standard Next.js multi-page app:

1.  **Create New Files:**
    * Create `pages/index.js` and copy the `EntryPage` component into it.
        (This will be your app's entry point, '/')
    * Create `pages/home.js` and copy the `HomePage` component into it.
    * Create `pages/leaderboard.js` and copy the `LeaderboardPage` component.
    * Create `pages/hexploit.js` and copy the `HexploitPage` component.

2.  **Create a Layout Component:**
    * Create `components/Layout.js`.
    * Copy the `Layout`, `AnimatedPoro`, and `Navigation` components into it.
    * In `pages/home.js`, `pages/leaderboard.js`, etc., wrap the page's
        content with this new `<Layout>` component.
    * You will also need to create a `pages/_app.js` file to load global styles
        and wrap all pages in the layout if you want it to persist.

3.  **Update Navigation:**
    * In the `Navigation` component, replace the `<a>` tags with Next.js's
        `<Link>` component.
    * Example:
        <a onClick={() => onNavigate('home')} ...> becomes:
        <Link href="/home">
          <a className={...}>...</a>
        </Link>
    * Do the same for all buttons that navigate between pages.

4.  **Styling:**
    * Create a `styles/globals.css` file and import it in `pages/_app.js`.
    * Add your custom fonts (like the "Beaufort for LOL" from the design)
        and custom CSS for the graphic borders here.

================================================================================
*/


//==============================================================================
// 1. ANIMATED COMPONENT (Bonus)
//==============================================================================

/**
 * An animated, interactive creature for the corner of the screen.
 * I've made a simple SVG Poro-like creature.
 * It has a subtle floating animation and a fun "spin" on click.
 */
const AnimatedPoro = () => {
  const [isClicked, setIsClicked] = useState(false);

  const handleClick = () => {
    setIsClicked(true);
    // Reset the animation class after it finishes
    setTimeout(() => setIsClicked(false), 500);
  };

  return (
    <>
      {/*
        This <style jsx> block is a Next.js feature. It scopes CSS to this
        component. This is how we can add custom keyframe animations
        without a separate CSS file.
      */}
      <style jsx>{`
        .poro-container {
          animation: float 3s ease-in-out infinite;
          transform-origin: bottom center;
        }

        .poro-clickable:hover {
          transform: scale(1.05);
          filter: drop-shadow(0 0 10px rgba(255, 255, 255, 0.5));
        }

        .poro-spin {
          animation: spin 0.5s ease-out;
        }

        @keyframes float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-15px); }
        }

        @keyframes spin {
          0% { transform: rotate(0deg) scale(1.1); }
          100% { transform: rotate(360deg) scale(1); }
        }
      `}</style>

      <div className="poro-container fixed bottom-8 left-8 z-50">
        <div
          className={`poro-clickable cursor-pointer transition-transform duration-300 ${isClicked ? 'poro-spin' : ''}`}
          onClick={handleClick}
          title="Hey!"
        >
          {/* A simple SVG Poro. You can replace this with an image or 3D model */}
          <svg width="100" height="100" viewBox="0 0 200 200" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M100 170C144.183 170 180 134.183 180 90C180 45.8172 144.183 10 100 10C55.8172 10 20 45.8172 20 90C20 134.183 55.8172 170 100 170Z" fill="white"/>
            <path d="M70 80C75.5228 80 80 75.5228 80 70C80 64.4772 75.5228 60 70 60C64.4772 60 60 64.4772 60 70C60 75.5228 64.4772 80 70 80Z" fill="#333"/>
            <path d="M130 80C135.523 80 140 75.5228 140 70C140 64.4772 135.523 60 130 60C124.477 60 120 64.4772 120 70C120 75.5228 124.477 80 130 80Z" fill="#333"/>
            <path d="M100 110C111.046 110 120 101.046 120 90H80C80 101.046 88.9543 110 100 110Z" fill="#F2994A"/>
            <path d="M40 100C40 111.046 31.0457 120 20 120C8.9543 120 0 111.046 0 100C0 88.9543 8.9543 80 20 80C31.0457 80 40 88.9543 40 100Z" fill="#A0E9FF"/>
            <path d="M200 100C200 111.046 191.046 120 180 120C168.954 120 160 111.046 160 100C160 88.9543 168.954 80 180 80C191.046 80 200 88.9543 200 100Z" fill="#A0E9FF"/>
            <path d="M80 140C80 145.523 75.5228 150 70 150C64.4772 150 60 145.523 60 140C60 134.477 64.4772 130 70 130C75.5228 130 80 134.477 80 140Z" fill="#FFB6C1"/>
            <path d="M140 140C140 145.523 135.523 150 130 150C124.477 150 120 145.523 120 140C120 134.477 124.477 130 130 130C135.523 130 140 134.477 140 140Z" fill="#FFB6C1"/>
          </svg>
        </div>
      </div>
    </>
  );
};

//==============================================================================
// 2. NAVIGATION COMPONENT
//==============================================================================

/**
 * The main site navigation bar.
 * `onNavigate` is a function passed from the main App to change the page state.
 * `currentPage` is used to highlight the active link.
 *
 * REFACTOR: Replace `onNavigate` with Next.js <Link> components.
 */
const Navigation = ({ onNavigate, currentPage }) => {
  const navItems = [
    { name: 'Home', page: 'home' },
    { name: 'Leaderboard', page: 'leaderboard' },
    { name: 'Hexploit Showdown', page: 'hexploit' },
  ];

  // Placeholder for the user profile section
  const UserProfile = () => (
    <div className="flex items-center space-x-3">
      <div className="w-10 h-10 rounded-full bg-gray-700 border-2 border-cyan-400">
        {/* Placeholder for user avatar */}
      </div>
      <span className="text-white font-semibold">Username</span>
    </div>
  );

  return (
    <nav className="fixed top-0 left-0 right-0 h-20 bg-black bg-opacity-50 backdrop-blur-md z-40 flex items-center justify-between px-8">
      {/*
        This is a placeholder for the complex border from the Figma design.
        You would replace this div with an `img` tag or a CSS background-image
        set to a custom border graphic.
      */}
      <div className="absolute inset-0 border-b-2 border-cyan-500 opacity-30 pointer-events-none"></div>

      <div className="text-2xl font-bold text-white tracking-widest uppercase">
        Rift Rewind
      </div>

      <div className="flex items-center space-x-8">
        {navItems.map((item) => {
          const isActive = currentPage === item.page;
          return (
            <a
              key={item.name}
              onClick={() => onNavigate(item.page)}
              className={`cursor-pointer uppercase tracking-wider text-lg font-medium transition-all duration-300
                ${isActive
                  ? 'text-cyan-300 scale-110'
                  : 'text-gray-400 hover:text-white'
                }`}
            >
              {/* REFACTOR: <Link href={`/${item.page}`}><a>{item.name}</a></Link> */}
              {item.name}
            </a>
          );
        })}
      </div>

      <UserProfile />
    </nav>
  );
};


//==============================================================================
// 3. LAYOUT COMPONENT
//==============================================================================

/**
 * A wrapper for all pages *except* the entry page.
 * Includes the Navigation and AnimatedPoro.
 */
const Layout = ({ children, onNavigate, currentPage }) => {
  return (
    <div className="relative min-h-screen w-full">
      {/*
        This is a placeholder for the background.
        The design uses a space/galaxy image.
      */}
      <div className="absolute inset-0 bg-gray-900 z-0">
        {/* Placeholder for galaxy background image */}
      </div>

      <Navigation onNavigate={onNavigate} currentPage={currentPage} />
      <AnimatedPoro />

      {/* Page Content */}
      <main className="relative z-10 pt-28 pb-16 px-8">
        {children}
      </main>
    </div>
  );
};


//==============================================================================
// 4. "PAGES" (COMPONENTS)
//==============================================================================

//------------------------------------------------------------------------------
// PAGE 1: ENTRY
// (This would be `pages/index.js`)
//------------------------------------------------------------------------------
const EntryPage = ({ onEnter }) => {
  return (
    <div className="min-h-screen w-full flex flex-col items-center justify-center bg-gray-900 text-white p-8">
      {/* Placeholder for the galaxy background */}

      {/* // TODO: Address this causing compilation error generated by Gemini and meanwhile disabled
      <Head>
        <title>Welcome to Rift Rewind</title>
      </Head>
      */}

      <div className="text-center">
        {/* Placeholder for the main logo */}
        <h1 className="text-7xl font-bold uppercase tracking-widest mb-4">
          Rift Rewind
        </h1>
        <p className="text-2xl text-cyan-300 mb-12">
          Replay. Relearn. Conquer.
        </p>

        {/*
          REFACTOR: This button would navigate to the /home route.
          <Link href="/home"><a ...>Enter</a></Link>
        */}
        <button
          onClick={onEnter}
          className="bg-cyan-500 text-gray-900 font-bold uppercase text-2xl px-16 py-4 rounded-lg
                     transition-all duration-300 transform hover:scale-105
                     hover:bg-cyan-400 shadow-lg shadow-cyan-500/30"
        >
          Enter
        </button>
      </div>

      {/* Placeholder for the bottom graphic elements */}
      <div className="absolute bottom-0 left-0 right-0 h-20 border-t-2 border-cyan-600 opacity-20"></div>
    </div>
  );
};

//------------------------------------------------------------------------------
// PAGE 2: HOME
// (This would be `pages/home.js`)
//------------------------------------------------------------------------------
const HomePage = ({ onNavigate }) => {
  return (
    <div className="text-white">
      {/*
      <Head>
        <title>Home - Rift Rewind</title>
      </Head>
      */}

      <div className="text-center mb-16">
        <h1 className="text-5xl font-bold mb-2">Welcome, Summoner</h1>
        <p className="text-xl text-gray-400">Select a game mode to begin.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
        {/* Hexploit Showdown Card */}
        {/* REFACTOR: <Link href="/hexploit"><a ...>...</a></Link> */}
        <div
          onClick={() => onNavigate('hexploit')}
          className="bg-gray-800 bg-opacity-70 rounded-lg p-8 cursor-pointer
                     border-2 border-transparent hover:border-cyan-400 transition-all duration-300
                     transform hover:-translate-y-2"
        >
          {/* Placeholder for card graphic */}
          <div className="w-full h-48 bg-gray-700 rounded mb-4 flex items-center justify-center">
            <span className="text-gray-500">Hexploit Graphic</span>
          </div>
          <h2 className="text-3xl font-bold mb-2 text-cyan-300">Hexploit Showdown</h2>
          <p className="text-gray-300">
            Analyze your micro-plays, optimize your combos, and outsmart your
            opponents in critical 1v1 scenarios.
          </p>
        </div>

        {/* Leaderboard Card */}
        {/* REFACTOR: <Link href="/leaderboard"><a ...>...</a></Link> */}
        <div
          onClick={() => onNavigate('leaderboard')}
          className="bg-gray-800 bg-opacity-70 rounded-lg p-8 cursor-pointer
                     border-2 border-transparent hover:border-yellow-400 transition-all duration-300
                     transform hover:-translate-y-2"
        >
          {/* Placeholder for card graphic */}
          <div className="w-full h-48 bg-gray-700 rounded mb-4 flex items-center justify-center">
            <span className="text-gray-500">Leaderboard Graphic</span>
          </div>
          <h2 className="text-3xl font-bold mb-2 text-yellow-300">Leaderboard</h2>
          <p className="text-gray-300">
            See how you stack up against other players. Climb the ranks and
            prove your mastery.
          </p>
        </div>
      </div>
    </div>
  );
};


//------------------------------------------------------------------------------
// PAGE 3: LEADERBOARD
// (This would be `pages/leaderboard.js`)
//------------------------------------------------------------------------------
const LeaderboardPage = () => {
  // Mock data based on the screenshot
  const topPlayers = [
    { rank: 2, name: 'Player 2', xyz: 'XYZ', rp: 2531, avatar: 'https://placehold.co/100x100/334155/94a3b8?text=P2', border: 'border-yellow-400' }, // Gold
    { rank: 1, name: 'Player 2', xyz: 'XYZ', rp: 2531, avatar: 'https://placehold.co/100x100/334155/94a3b8?text=P1', border: 'border-gray-300' }, // Silver
    { rank: 3, name: 'Player 2', xyz: 'XYZ', rp: 2531, avatar: 'https://placehold.co/100x100/334155/94a3b8?text=P3', border: 'border-yellow-700' }, // Bronze
  ];

  const leaderboardData = [
    { player: 'Player A', rank: 'ABC', xyz1: 'ABC', xyz2: 'ABC', xec: 'XBC' },
    { player: 'Player B', rank: 'XYI', xyz1: 'ABC', xyz2: 'XYI', xec: 'ABC' },
    { player: 'Player C', rank: 'YOU', xyz1: 'ABC', xyz2: 'ABC', xec: 'YOU' },
    { player: 'Player D', rank: 'YOU', xyz1: 'XOU', xyz2: 'ABC', xec: 'XOU' },
    { player: 'Player E', rank: 'ABC', xyz1: 'ABC', xyz2: 'ABC', xec: 'XBC' },
    { player: 'Player F', rank: 'XYI', xyz1: 'ABC', xyz2: 'XYI', xec: 'ABC' },
  ];

  // Helper for the top 3 pods
  const PlayerPod = ({ player, isCenter }) => (
    <div className={`relative flex flex-col items-center ${isCenter ? 'scale-110 -translate-y-4 z-10' : 'scale-90'}`}>
      {/* This is a placeholder for the custom frame graphic */}
      <div className={`w-48 h-64 rounded-xl bg-gray-800 bg-opacity-50 border-4 ${player.border} p-4 flex flex-col items-center justify-center`}>
        <span className="text-white font-bold">{player.name}</span>
        <img src={player.avatar} alt={player.name} className="w-24 h-24 rounded-full my-4 border-2 border-white/50" />
        <span className="text-gray-300">{player.xyz}</span>
        <span className="text-cyan-300 font-bold">{player.rp} RP</span>
      </div>
    </div>
  );

  return (
    <div className="text-white max-w-7xl mx-auto">
      {/*
      <Head>
        <title>Leaderboard - Rift Rewind</title>
      </Head>
      */}

      {/* Top 3 Players - Based on screenshot */}
      <div className="relative flex justify-center items-center space-x-4 mb-12 h-80">
        {/* Placeholder for the background frame graphic */}
        <div className="absolute w-3/4 h-3/4 border-2 border-cyan-500/30 rounded-lg top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"></div>

        <PlayerPod player={topPlayers[1]} /> {/* Rank 2 (Silver) */}
        <PlayerPod player={topPlayers[0]} isCenter /> {/* Rank 1 (Gold) */}
        <PlayerPod player={topPlayers[2]} /> {/* Rank 3 (Bronze) */}
      </div>

      {/* Main Leaderboard Table */}
      <div className="bg-gray-900 bg-opacity-70 p-6 rounded-lg border-2 border-cyan-500/30">
        {/* This is a placeholder for the custom table frame */}
        <h2 className="text-3xl font-bold uppercase tracking-wider text-cyan-300 mb-4">Leaderboard</h2>
        <table className="w-full text-left">
          <thead>
            <tr className="border-b border-gray-700">
              <th className="p-3 uppercase text-gray-400">Player</th>
              <th className="p-3 uppercase text-gray-400">Rank</th>
              <th className="p-3 uppercase text-gray-400">XYZ</th>
              <th className="p-3 uppercase text-gray-400">XYZ</th>
              <th className="p-3 uppercase text-gray-400">XEC</th>
            </tr>
          </thead>
          <tbody>
            {leaderboardData.map((row, index) => (
              <tr key={index} className="border-b border-gray-800 hover:bg-gray-800/50">
                <td className="p-3 font-semibold">{row.player}</td>
                <td className="p-3">{row.rank}</td>
                <td className="p-3">{row.xyz1}</td>
                <td className="p-3">{row.xyz2}</td>
                <td className="p-3">{row.xec}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

//------------------------------------------------------------------------------
// PAGE 4: HEXPLOIT SHOWDOWN
// (This would be `pages/hexploit.js`)
//------------------------------------------------------------------------------
const HexploitPage = () => {
  return (
    <div className="text-white max-w-4xl mx-auto text-center">
      {/*
      <Head>
        <title>Hexploit Showdown - Rift Rewind</title>
      </Head>
      */}

      {/* Placeholder for the header graphic */}
      <div className="w-full h-56 bg-gray-700 rounded-lg mb-8 flex items-center justify-center border-2 border-cyan-500/30">
        <span className="text-gray-500">Hexploit Header Graphic</span>
      </div>

      <h1 className="text-6xl font-bold text-cyan-300 mb-4 uppercase tracking-wider">
        Hexploit Showdown
      </h1>
      <p className="text-xl text-gray-300 mb-12 leading-relaxed">
        Step into the arena and analyze your performance in critical moments.
        Upload a replay, select a showdown, and let our AI break down your
        micro-decisions, combo execution, and positioning.
      </p>

      {/*
        REFACTOR: This button would likely lead to a new page or open a modal.
        For now, it's just a button.
      */}
      <button
        className="bg-cyan-500 text-gray-900 font-bold uppercase text-2xl px-16 py-4 rounded-lg
                   transition-all duration-300 transform hover:scale-105
                   hover:bg-cyan-400 shadow-lg shadow-cyan-500/30"
      >
        Start Analysis
      </button>
    </div>
  );
};


//==============================================================================
// 5. MAIN APP (THE ACTUAL NEXT.JS PAGE)
//==============================================================================

/**
 * This is the main component that Next.js will render for the `/` route.
 * It holds the `currentPage` state and renders the correct "Page" component.
 */
export default function IndexPage() {
  const [currentPage, setCurrentPage] = useState('entry'); // 'entry', 'home', 'leaderboard', 'hexploit'

  // A simple function to change the page.
  // REFACTOR: This will be replaced by Next.js's router.
  const navigate = (page) => {
    setCurrentPage(page);
  };

  // Render the correct page based on state
  const renderPage = () => {
    if (currentPage === 'entry') {
      return <EntryPage onEnter={() => navigate('home')} />;
    }

    // All other pages are wrapped in the Layout
    return (
      <Layout onNavigate={navigate} currentPage={currentPage}>
        {currentPage === 'home' && <HomePage onNavigate={navigate} />}
        {currentPage === 'leaderboard' && <LeaderboardPage />}
        {currentPage === 'hexploit' && <HexploitPage />}
      </Layout>
    );
  };

  return (
    <div className="font-sans"> {/* REFACTOR: Add your custom LOL font here */}
      {/*
      <Head>
        {/* This is the default title, individual pages will override it * /}
        <title>Rift Rewind</title>
        <meta name="description" content="Rift Rewind Hackathon Project" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      */}

      {renderPage()}
    </div>
  );
}